/* Generated by /Users/Sargon/Downloads/ATLAS/buildDir/..//CONFIG/src/probe_aff.c */
#ifndef ATL_TAFFINITY_H
   #define ATL_TAFFINITY_H

#define ATL_HAS_AFFINITY 0
#define ATL_PAFF_NONE 1
#define ATL_NOAFFINITY 1

#endif /* end multiple inclusion guard */
