#ifndef ATL_INSTINFO_H
   #define ATL_INSTINFO_H

#define ATL_ARCH "UNKNOWNx8664AVXMAC"
#define ATL_INSTFLAGS "-1 0 -a 1 -l 1"
#define ATL_F2CDEFS "-DAdd_ -DF77_INTEGER=int -DStringSunStyle"
#define ATL_ARCHDEFS "-DATL_OS_OSX -DATL_ARCH_UNKNOWNx86 -DATL_CPUMHZ=2900 -DATL_AVXMAC -DATL_AVX -DATL_SSE3 -DATL_SSE2 -DATL_SSE1 -DATL_USE64BITS -DATL_GAS_x8664"
#define ATL_DKCFLAGS "-O -fomit-frame-pointer -mavx2 -mfma -m64"
#define ATL_DKC "/usr/local/bin/gcc-5"
#define ATL_SKCFLAGS "-O -fomit-frame-pointer -mavx2 -mfma -m64"
#define ATL_SKC "/usr/local/bin/gcc-5"
#define ATL_DMCFLAGS "-O -fomit-frame-pointer -mavx2 -mfma -m64"
#define ATL_DMC "/usr/local/bin/gcc-5"
#define ATL_SMCFLAGS "-O -fomit-frame-pointer -mavx2 -mfma -m64"
#define ATL_SMC "/usr/local/bin/gcc-5"
#define ATL_ICCFLAGS "-DL2SIZE=4194304 -I/Users/Sargon/Downloads/ATLAS/buildDir/include -I/Users/Sargon/Downloads/ATLAS/buildDir/..//include -I/Users/Sargon/Downloads/ATLAS/buildDir/..//include/contrib -DAdd_ -DF77_INTEGER=int -DStringSunStyle -DATL_OS_OSX -DATL_ARCH_UNKNOWNx86 -DATL_CPUMHZ=2900 -DATL_AVXMAC -DATL_AVX -DATL_SSE3 -DATL_SSE2 -DATL_SSE1 -DATL_USE64BITS -DATL_GAS_x8664 -m64 -DATL_NCPU=4 -O -fomit-frame-pointer -mavx2 -mfma -m64"
#define ATL_ICC "/usr/local/bin/gcc-5"
#define ATL_F77FLAGS "-O -mavx2 -mfma -m64"
#define ATL_F77 "/usr/local/bin/gfortran"
#define ATL_DKCVERS "gcc-5 (Homebrew gcc 5.2.0) 5.2.0"
#define ATL_SKCVERS "gcc-5 (Homebrew gcc 5.2.0) 5.2.0"
#define ATL_DMCVERS "gcc-5 (Homebrew gcc 5.2.0) 5.2.0"
#define ATL_SMCVERS "gcc-5 (Homebrew gcc 5.2.0) 5.2.0"
#define ATL_ICCVERS "gcc-5 (Homebrew gcc 5.2.0) 5.2.0"
#define ATL_F77VERS "GNU Fortran (Homebrew gcc 5.2.0) 5.2.0"
#define ATL_SYSINFO "Darwin dn156-062.naist.jp 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184 3/RELEASE_X86_64 x86_64"
#define ATL_DATE    "Wed Jun 15 13:43:00 JST 2016"
#define ATL_UNAM    "root"
#define ATL_VERS    "3.10.2"

#endif
